workspace = { members = ["procedural_macros"]}

[package]
name = "generate_es_search_query"
version = "0.1.0"
edition = "2021"

[dependencies]
es_search_query_procedural_macros = {path = "./procedural_macros"}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
